spring:
  application:
    name: api-monitora-mais
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
integration:
  suap:
    url: ${SUAP_URL}
    credential: ${SUAP_CREDENTIAL}
    key: ${SUAP_KEY}

security:
  jwt:
    key: ${JWT_KEY}
    access-expires-in: ${JWT_ACCESS_EXPIRES_IN} #15 minutes
    refresh-expires-in: ${JWT_REFRESH_EXPIRES_IN} #7 days
